# Generated by Django 4.1.6 on 2023-03-02 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('manzil', models.CharField(max_length=50)),
                ('ism', models.CharField(max_length=25)),
                ('tel', models.CharField(max_length=16)),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assos_app.ombor')),
            ],
        ),
    ]
