# Generated by Django 4.1.6 on 2023-03-02 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assos_app', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='qarz',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('brend', models.CharField(max_length=50)),
                ('miqdor', models.PositiveSmallIntegerField()),
                ('narx', models.PositiveIntegerField()),
                ('olchov', models.CharField(max_length=15)),
                ('kelgan_sana', models.DateTimeField(auto_now_add=True)),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assos_app.ombor')),
            ],
        ),
    ]
