# Generated by Django 4.1.6 on 2023-03-03 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assos_app', '0003_client_qarz_mahsulot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ombor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clintlar', to='assos_app.ombor'),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='ombor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulotlar', to='assos_app.ombor'),
        ),
    ]
