# Generated by Django 4.1.6 on 2023-03-04 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assos_app', '0004_alter_client_ombor_alter_mahsulot_ombor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ombor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
